### ISSUE TITLE
Cannot generate with Ubuntu

### ISSUE THREAD

**Issue by evamaxfield** [quarto-journals/acm#17]
Hello! I was attempting to use the ACM journal output format for my project but unfortunately I can't seem to get it to work. I have ever tried rendering the basic example and it fails.

Environment:
quarto: 1.3.191
r-tinytex: 0.44
texlive-core: 20210325
ubuntu: 22.04

Reproduction:
```
quarto use template quarto-journals/acm
## Directory name: test

cd test
quarto render test.qmd --to acm-pdf
```

Error:
```
compilation failed- missing packages (automatic installed disabled)
LaTeX Error: File `acmart.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.2 ^^M
```

Any help would be great appreciated.

**Comment by dragonstyle** [comment]
It looks like the `acmart` package is missing from LaTeX on your machine. You should be able to install it using the command:

`tlmgr install acmart`

We generally recommend using TinyTeX (`quarto install tinytex`) to help make package installation easier as it will automatically download missing packages, but if you already have a TeX installation that you're happy with, the above should work.

Hth!

**Comment by evamaxfield** [comment]
Wow. Thanks for telling me about `quarto install tinytex`. I have never come across that in the documentation which is why I had weird tinytex and texlive versions. That solved the issue!

**Comment by cscheid** [comment]
@evamaxfield If something doesn't work with this format, please don't hesitate to contact me directly at carlos.scheidegger@posit.co - we want to make sure that this is a great experience for folks considering quarto to venues like CHI, etc. Thanks!
