### ISSUE TITLE
Error running filter _extensions/quarto-journals/acm/add-bibliography.lua

### ISSUE THREAD

**Issue by erinmr** [quarto-journals/acm#3]
Hi - I was testing out the ACM template and ran into this error: 
```

Error running filter _extensions/quarto-journals/acm/add-bibliography.lua:
PandocLuaError "Cannot get Attr from TypeNil"
stack traceback:
	_extensions/quarto-journals/acm/add-bibliography.lua:54: in function <_extensions/quarto-journals/acm/add-bibliography.lua:53>
```

I'm not sure how to proceed troubleshooting this one. Any help would be great. Thanks so much!

**Comment by erinmr** [comment]
I got this error when I tried to convert a qmd to the ACM template. When I use the template to start, I don't get this error, so I think I'm all set for now.

**Comment by dragonstyle** [comment]
Thanks for reporting - it is likely something that we're inadvertently depending upon in the document yaml. If you do want to share that document (if you can) - I'll be happy to have the reproducible case so I can get it fixed! If not, no worries and lmk if you run into it again!

**Comment by erinmr** [comment]
Hi Charles - I recreated the error. I was doing something wrong with the abstract in the YAML. I don't know how to properly format that. I am attaching a screenshot of what it looks like.
![Screen Shot 2022-08-19 at 9 57 54 AM](https://user-images.githubusercontent.com/2915555/185659324-6ddad6d8-ab8c-4066-a15b-f2a255aafec1.png)

This one works: 
![Screen Shot 2022-08-19 at 9 58 14 AM](https://user-images.githubusercontent.com/2915555/185659375-da839c65-5b19-4292-8eb4-4f04860092b6.png)
