### ISSUE TITLE
BibTex parsed incorrectly when using acm-pdf

### ISSUE THREAD

**Issue by ulyngs** [quarto-journals/acm#5]
References that work in a normal quarto or R Markdown document break when using the `acm-pdf` format.

Take this example bibtex entry:

**references.bib**:
```bibtex
@Article{koNUGUGroupbasedIntervention2015,
  title = {{{NUGU}}: {{A Group}}-Based {{Intervention App}} for {{Improving Self}}-{{Regulation}} of {{Limiting Smartphone Use}}},
  author = {Minsam Ko and Kyong-Mee Chung and Subin Yang and Joonwon Lee and Christian Heizmann and Jinyoung Jeong and Uichin Lee and Daehee Shin and Koji Yatani and Junehwa Song},
  date = {2015},
  journaltitle = {Proceedings of the 18th ACM Conference on Computer Supported Cooperative Work \& Social Computing - CSCW '15},
  pages = {1235--1245},
  doi = {10.1145/2675133.2675244}
}
```

## It doesn't work in acm-pdf

**test.qmd**:
```markdown
---
title: "test"
format: acm-pdf
bibliography: references.bib
acm-metadata:
  copyright: acmcopyright
---

# Introduction

Test [@koNUGUGroupbasedIntervention2015].

# References {-}

::: {#refs}
:::
```

<img width="775" alt="image" src="https://user-images.githubusercontent.com/23137032/185750369-1faa9dae-2988-475d-af2f-25c73cbc2e48.png">

## It works in normal pdf output

**test.qmd**:
```markdown
---
title: "test"
format: pdf
bibliography: references.bib
---

# Introduction

Test [@koNUGUGroupbasedIntervention2015].

# References {-}

::: {#refs}
:::
```

<img width="884" alt="image" src="https://user-images.githubusercontent.com/23137032/185750595-6f8e42b9-61c8-4eec-b47e-80e0f3195921.png">

## It also works in acm-html output
**test.qmd**:
```markdown
---
title: "test"
format: acm-html
bibliography: references.bib
acm-metadata:
  copyright: acmcopyright
---

# Introduction

Test [@koNUGUGroupbasedIntervention2015].

# References {-}

::: {#refs}
:::
```

<img width="980" alt="image" src="https://user-images.githubusercontent.com/23137032/185750514-64eb1a26-4210-4b5b-9a9e-0568d0e8639d.png">

**Comment by reagle** [comment]
Relatedly:

1. Is `date` supported, or must we use `year`?
2. Could we actually use YAML and CSL?

**Comment by ulyngs** [comment]
@cderv might you know why this is occurring? Happy submit a PR so solve it, if I can get a pointer about what to do!

**Comment by cscheid** [comment]
@ulyngs Are you running the latest version of quarto? on quarto 1.2.269 I see this:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/285675/201139931-1511f876-f4bf-4595-a6b1-dbbd4c021251.png">

I also noticed you seem to be getting the wrong font. I'm not sure how that's happening.

**Comment by ulyngs** [comment]
@cscheid upgraded to the latest version of quarto -- I can confirm that it's working now!!
