### ISSUE TITLE
Error running filter _extensions/quarto-journals/acm/add-bibliography.lua

### ISSUE THREAD

**Issue by soumyaray** [quarto-journals/acm#8]
I'm trying to Render a `.qmd` file that has as part of its front matter:

```rmd
format: acm-pdf
keep-tex: true

acm-metadata:
  final: true

  # lines omitted

  ccs:  # omitted
  keywords: # omitted 
```

When I hit render, I get the error:
```
Error running filter _extensions/quarto-journals/acm/add-bibliography.lua:
_extensions/quarto-journals/acm/add-bibliography.lua:57: attempt to call a nil value (field 'is_format')
stack traceback:
```

(no traceback is offered)

I just installed quarto and the quarto-journals/acm extension today, and have my RStudio is v2022.07.01

**Comment by Sumidu** [comment]
I installed Quarto and the ACM template today on a new machine and have the same issue. No problem on an older installation.

**Comment by Sumidu** [comment]
Oh, I think I found the problem. The default download for Quarto is v.1.1.xxx and it needs 1.2.xx. 

@soumyaray You can find the download for the pre-release of 1.2 here: https://quarto.org/docs/download/prerelease.html

**Comment by soumyaray** [comment]
This fixed it!! Thanks @Sumidu. I'll close the issue now as it seems to be just a back-compatibility issue, and @cscheid is welcome to reopen it if there is anything to be done on their side.

**Comment by cscheid** [comment]
We should add a warning to `quarto-journals` about running v1.2 pre-release versions.
